### ISSUE TITLE
Add callback for event send failure

### ISSUE THREAD

**Issue by mnussbaum** [getsentry/raven-java#180]
Opening this issue to get feeback about an idea for an error handler callback when an event fails to send to the Sentry server. This is definitely an edge case, but ensuring that exceptions aren't lost is important for our application stability.

The approach we're thinking of is adding an optional `onSendError` callback argument to `RavenFactory.ravenInstance`. The callback will take two arguments, the event that failed to send, and the exception that prevented sending. The callback will be passed down to the classes implementing `AbstractConnection`, and it will be invoked in [`ConnectionException` handler in `send`](https://github.com/getsentry/raven-java/blob/00abd1c998dd647ecfd879be1fc6fc9429334c11/raven/src/main/java/net/kencochrane/raven/connection/AbstractConnection.java#L81).

What do you think about this approach? If it sounds promising I'm happy to write a pull request.

**Comment by mnussbaum** [comment]
CC @jszwedko

**Comment by tkaemming** [comment]
I think this makes sense overall, and we'd love to check out a pull request.

A few offhand thoughts:

- I'm not sure it makes sense to expose this on the `RavenFactory` class at the moment. I think it'd make more sense to isolate the change at first to add the capability to the `AbstractConnection` class. To bind the callback, the user would need to use a different default factory (probably extending `DefaultRavenFactory`) and override `createConnection` to include the callback (probably as a constructor parameter to `AbstractConnection` implementations?)
- This could allow recursion issues if the error callback itself raised an exception. Any thoughts on how to address this?

+@bretthoerner

**Comment by jszwedko** [comment]
Hi @tkaemming !

The first thought seems sensible.

As for the second, it feels like the library should wrap the callback and trap any exceptions (perhaps just dumping a log line). I can definitely see the issue with recursing if your callback fired an additional event, I'll have to think about how that can be addressed cleanly.

**Comment by bretthoerner** [comment]
Sorry for the late reply. First, I agree with both of @tkaemming's points.

Preventing the callback from causing another Sentry event is going to be the hard part, I think. Especially since users are going to be writing their own callbacks. The only thing I can think of is using the pattern that's already established in `RavenEnvironment`: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/environment/RavenEnvironment.java#L35-L74

This means callbacks would need to careful not to put work on other threads, because if they do all bets are off... :(

A PR would be a great starting point, though. I may be able to take a stab as this would be helpful with Android too, I believe.
