### ISSUE TITLE
Set Default Queue Size

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/raven-java#212]
Currently the queue size is unbounded by default in async mode which could cause days of backlog on the events. We have a customer who sends days old events from an earlier outage after the network recovered.

**Comment by mitsuhiko** [comment]
Alternatively we could set a max age i suppose.

**Comment by francisdb** [comment]
Some more context:

We have logback event reporting set up (warning and error)

We had huge database problems last week, this has been fixed 2 days ago. The service that uses that database was not restarted during that time and today we still see events coming in from 3-4 days ago.

Also the sentry dashboard reports 2500 events per hour coming in which made me worry that events got lost. But we of course see no recent data because these events are all added to the past.

We of course don't want this old events flood to make that we lose today's events because of applied quota.

**Comment by bretthoerner** [comment]
I think this makes sense. We can set a default and offer an option. One thing though,

> made me worry that events got lost

Just to be clear, adding this *will* cause events to be lost.

**Comment by francisdb** [comment]
hehe, indeed, but I am more worried about sparse events from today than thousands of similar bulk events from 3 days ago.
I guess some bound queue + time to live on events would be best?

**Comment by tkaemming** [comment]
Some thought fragments: ideally, we'd be able to maintain a relatively representative sample of events that ensures new events are preferred to be delivered to the Sentry server earlier, while not totally dropping older events. If we were to use a bounded FIFO queue, this would cause the sample to be biased (probably an understatement) towards older events at the expense of dropping newer events. If were were to use a circular buffer, this would cause the sample to be biased towards newer events at the expense of losing data about older events. A reasonable compromise might be to implement some sort of [weighted random sampling](https://en.wikipedia.org/wiki/Reservoir_sampling#Weighted_Random_Sampling_using_Reservoir) when the queue grows beyond it's capacity — ideally, we'd be able to implement this with a bounded priority queue, but no implementation exists in the Java standard library, so we'd have to implement one ourselves.

**Comment by francisdb** [comment]
Best would be to filter out

**Comment by tkaemming** [comment]
I'm not sure that I understand, filtering on what criteria?

**Comment by tkaemming** [comment]
Oops, just saw that this was edited on the web UI. We do all of the normalization and aggregation on the server side and would like to avoid reimplementing that behavior in the SDK but maybe there's something we can do on the SDK side that doesn't introduce too much complexity.

**Comment by bretthoerner** [comment]
A couple thoughts:

1. The low hanging fruit we could release right away is to set a new default queue bound here: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java#L146

We'd also want to support something like `-1` to disable the queue (I think?).

Does this seem like something we should do? Any thoughts on default sizing?

2. For sampling I think we can pretty easily make use of something like this: https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/stats/ReservoirSampler.java

We'd need to add a way to grab an item off the end. The problem is that we'd also be leaving the Java Concurrent collection behind (`LinkedBlockingQueue`), and so we'd have to synchronize the whole `send` call in `AsyncConnection` and also whatever `fetch` method we create on the other side. I... can't imagine a use case where a user is going to be critically bound on attempting to send exceptions to Sentry... but it's something we need to consider.

**Comment by tkaemming** [comment]
> Any thoughts on default sizing?

My initial thoughts: probably no more than a one minute backlog on the Medium plan (50 events)?

**Comment by bretthoerner** [comment]
Default value of 50 is in master, do we have strong opinions on whether sampling should be done now, or should we revisit after the default limit is out for a while?

**Comment by tkaemming** [comment]
I think releasing with the GH-221 makes sense now. I think that sampling would be a more ideal implementation, but I don't think that needs to be a high priority at the moment.
