### ISSUE TITLE
Java Error: NoClassDefFoundError

### ISSUE THREAD

**Issue by maeyrl** [getsentry/raven-java#230]
Error: http://hastebin.com/ififagener.avrasm
Pom: http://hastebin.com/laxovixego.xml
If any more information is needed, please tell me. I need this error fixed asap.

**Comment by bretthoerner** [comment]
It seems like the `raven-log4j` jar and its dependencies aren't on your classpath at runtime. Is there a way for you to verify/list all your runtime jars?

**Comment by maeyrl** [comment]
I am not sure how to do that, Is there an IntelliJ/CMD way to list that??

**Comment by bretthoerner** [comment]
It wouldn't really be in IntelliJ. I'm gathering this is Minecraft related, how are you deploying the Raven client? Do you copy some `jar` files into a directory on a server somewhere, or?

**Comment by maeyrl** [comment]
I just compile the jar via a maven compiler and then put it on a server and that is the output.

**Comment by bretthoerner** [comment]
So my guess is that the jar you're building is just `mcm110` and not its dependencies. This is common, users will typically build something like an uberjar (containing all deps) if they're deploying a single application. Because you're embedding this in something else (Minecraft) you may need to do some more manual dependency management than usual.

You say you "put it on the server", can you list the jars in that directory? Given the error, I'm 99% sure you're missing the `Raven` jars. You could try manually downloading and putting these on the server also:

http://search.maven.org/remotecontent?filepath=com/getsentry/raven/raven-log4j/7.4.0/raven-log4j-7.4.0.jar

http://search.maven.org/remotecontent?filepath=com/getsentry/raven/raven/7.4.0/raven-7.4.0.jar

You may also need Raven's dependencies, such as Jackson, etc... this is why doing it manually stinks. I'm not familiar with Minecraft servers or how people usually handle this there.
