### ISSUE TITLE
Add Argument to Disable Raven in Development

### ISSUE THREAD

**Issue by caseyoneill** [getsentry/raven-java#244]
It would be really nice to have a VM or Program argument that we can set in development environments. That way the entire team won't be spammed with dev crashes while developing new features and we also won't have to worry about someone accidentally checking in their disabled log file.

**Comment by bretthoerner** [comment]
Typically this is done by not configuring a DSN in development mode. Is
there a reason that won't work for you?

**Comment by caseyoneill** [comment]
Are you referring to commenting out the log4j.appender.SentryAppender.dsn line in log4j.properties? Is there another way to disable the DSN through a VM or Program argument?

**Comment by bretthoerner** [comment]
Your DSN can also come from your environment or a Java system property (instead of log4j config). I think the best way to handle differences between environments (such as production vs development) is to leave the DSN out of your logging config entirely and set the `SENTRY_DSN` environment variable or system property only on production, which is the same (or exactly the opposite :smile:) of adding an *additional* environment variable or system property as you mentioned.

**Comment by caseyoneill** [comment]
@bretthoerner Are these variables documented anywhere? I'm not seeing them listed in the README for https://github.com/getsentry/raven-java/tree/master/raven . Can you also set com.getsentry.raven.jul.SentryHandler.environment as an environment variable?

**Comment by bretthoerner** [comment]
It's poorly documented (we only show it in our examples repo AFAIK), I plan to fix that soon. Currently it's just the `DSN` that checks the environment. We should probably allow setting some other options that way too.

As the code is on `master` today you have to swap out your log configuration. :disappointed:

**Comment by bretthoerner** [comment]
This PR should help: https://github.com/getsentry/raven-java/pull/246

It's not on `master` yet, but you could use a custom build of this while it's being reviewed.

**Comment by caseyoneill** [comment]
This is perfect, thank you.
