### ISSUE TITLE
Uncaught exceptions (crashes) aren't sent in time

### ISSUE THREAD

**Issue by bgerstle** [getsentry/raven-java#251]
### Overview

Typically, crash reporters will persist crash data in the event it doesn't get sent immediately, e.g. sending crash events the next time a process is run.  `raven-java` doesn't appear to persist the data anywhere, so uncaught exceptions cannot be reported.  
### Steps to reproduce
1. Add `raven-java` to an Android project
2. Call `Raven.sendException` inside Java's uncaught exception handler*
3. Raise a `RuntimeException` (or other exception) outside of a try/catch block

\* For example:

``` java
Thread.getDefaultUncaughtExceptionHandler();
Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
  public void uncaughtException(Thread t, Throwable e) {
    Log.e("An uncaught exception occurred: " + e);
    Raven.sendException(e);
  }
});
```
### Expected results

Log is emitted immediately, and an event is sent to Sentry the next time the app is run.
### Actual results

Log is immediately sent, but the Sentry Event is never sent due to the app being terminated before transmission completes.  Is there another way to configure Sentry that I'm missing?
### Proposed solution

Store events in the [circular FIFO queue](https://github.com/getsentry/raven-java/blob/34798e1566d9b2f1473d7b19ec32ff53f742489f/raven/src/main/java/com/getsentry/raven/util/CircularFifoQueue.java) prior to transmission.  Remove them as they are sent, but in the event of an uncaught exception, serialize the queue to some configured path on disk. When `Raven` is initialized, it should attempt to restore the queue from data on disk at the configured location.

**Comment by bretthoerner** [comment]
Thanks for the detailed report. Because of our progress on Android (where this is a must) a lot of this legwork has been done. I think it's a good idea to allow non-Android users to configure a directory that stores exceptions for "the next run."

**Comment by bgerstle** [comment]
Hey, @bretthoerner glad to hear you folks are already thinking about this!  Is this functionality available in a snapshot build?

**Comment by bgerstle** [comment]
Ahh I see there's an `android-start` branch, I don't suppose it's production ready? 😬

**Comment by bgerstle** [comment]
> I think it's a good idea to allow non-Android users to configure a directory that stores exceptions for "the next run."

Couldn't agree more! IMHO a tool like Sentry should take reasonable measures to prevent data loss—especially for critical errors such as uncaught exceptions.

**Comment by bretthoerner** [comment]
Depends, are you using this for Android? That branch is definitely Android specific. And it's under review and subject to change -- plus we'd like to support more before we call it production, like collecting lots of app info in errors for you.

If you're not worried about Android these are the main entry points:

https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/connection/Connection.java#L24
https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/connection/EventSendFailureCallback.java

Although, as I typed this out I realized it's not exactly what you're after still (I'm going to leave the above just incase). There are two very different scenarios:

1. Attempt to send an async error fails (network down, common on Android)
2. Attempt to send an async error *never happens* because JVM exits

For 2... we'd have to pro-actively (and synchronously) write all exceptions to disk before we attempt to async send them via network, right?

**Comment by bgerstle** [comment]
> For 2... we'd have to pro-actively (and synchronously) write all exceptions to disk before we attempt to async send them via network, right?

That's one approach, albeit maybe a tad brute force. You can keep the circular queue in memory, then write it to disk quickly before the JVM exits.  Next time the `Raven` constructor is called, read the data from disk & resume processing the FIFO queue.

**Comment by bgerstle** [comment]
Writing it to disk is the most guarded option, since it will even prevent data loss during _really_ catastrophic events like kernel panics or the OS shutting down due to low power.

**Comment by bgerstle** [comment]
You could also choose based on level, for example:

- Never lose error events: write every one to disk before sending
- Keep other "messages" & breadcrumbs in memory to reduce I/O and preserve battery life

**Comment by bretthoerner** [comment]
I guess I was worrying about adding a shutdown hook to handle the buffer on exit, but we already have one on our async connection. Which makes me wonder why that isn't working (separate problem/question).

I'll check this out more this week. I think you're on to something though.

**Comment by bgerstle** [comment]
Keep in mind, there are two kinds of errors:

- Low-traffic, but fatal unexpected errors (runtime exceptions, failed assertions, etc.)
- Not-as-low-traffic, but recoverable errors (JSON parsing, etc.)

**Comment by bgerstle** [comment]
> we already have one on our async connection. 

Interesting, I didn't see any queues in the [`AsyncConnection` class](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java).

> are you specifically interested in Android or server?

Android

**Comment by bretthoerner** [comment]
It's not queues, no queue will help you when your app exits. We have a shutdown hook: 

https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java#L93

Which is supposed to wait up to N seconds to exit (waiting on the executor, which itself has a queue):

https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/connection/AsyncConnection.java#L135

But I guess it's not working as expected. This predates me, so I'll have to think about it some.

All that said, if you're after Android support you may want to check out the PR. We don't handle unexpected crashes very well yet though -- again, it would have to be a JVM shutdown hook (assuming Android even respects those?) AFAIK.

**Comment by bgerstle** [comment]
Yesterday I was running the tests with the debugger attached. Today, without the debugger, the app becomes unresponsive when I raise the runtime exception. I thought at first it could be waiting on that shutdown hook you mentioned, but I don't know if that's respected on Android after a crash.

I also tried reporting an exception (without raising it) in my `Application.onTerminate` method, and it also appears to have failed at sending the event.

**Comment by bretthoerner** [comment]
Some questions,

* Is this using a release from Maven or the branch?
* How are you configuring your Raven client?
* I take it this a "toplevel" unhandled exception, and not an exception object that you pass to `Raven.capture`?
* When you say becomes unresponsive, do you mean hangs and takes no input, or crashes?

**Comment by bgerstle** [comment]
> Is this using a release from Maven (if so, which) or the Android branch?

7.7.0

> I take it this a "toplevel" unhandled exception, and not an exception object that you pass to Raven.capture?

Correct, raising a `RuntimeException` in a button click handler.

> When you say becomes unresponsive, do you mean hangs and takes no input, or crashes?

Unresponsive

**Comment by bretthoerner** [comment]
> How are you configuring your Raven client?

This one is really important to help me try and reproduce. :)

**Comment by bgerstle** [comment]
Ah, sorry I missed that one! I realize your docs strongly advise agains this, but I was sending the exceptions manually since we're not setup w/ SLF4J or equivalent at the moment. Our setup is effectively:

``` java
// at startup, create raven instances
RavenFactory.ravenInstance("DSN");

// setup uncaught exception handler
private void setupUncaughtExceptionHandler() {
  final Thread.UncaughtExceptionHandler defaultUncaughtExceptionHandler =    
    Thread.getDefaultUncaughtExceptionHandler();
  Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
    public void uncaughtException(Thread t, Throwable e) {
      Log.e("An uncaught exception occurred: " + e);
      Raven.capture(e);
      if (defaultUncaughtExceptionHandler != null) {
        defaultUncaughtExceptionHandler.uncaughtException(t, e);
      }
    }
  });
}
```

**Comment by bretthoerner** [comment]
Does your DSN include any options? I think you'll definitely need/want `?raven.async=false` (see https://github.com/getsentry/raven-java/blob/master/README.md)

Though, maybe you already have that set? I don't know how this would have worked in a debugger either. I guess to just rule things out, can you list your DSN options, if any?

**Comment by bgerstle** [comment]
No options currently, I think we need async set to true since Android will
crash if you perform networking on the main thread

**Comment by bretthoerner** [comment]
Yeah, you do. That'd be your issue -- Android will throw an exception, then the uncaught exception handler catches it... Raven tries to send... repeat.

It's still confusing to me that this worked with the debugger attached though.

Anyway, with Async on you should be good to go for a while. Our Android branch should land soon and will handle buffering items to disk while offline, etc.

**Comment by bgerstle** [comment]
> It's still confusing to me that this worked with the debugger attached though.

To be clear, this hasn't worked yet for me—debugger or not.

> Anyway, with Async on you should be good to go for a while

AFAICT it's on by default and it still didn't work. I'll be sure to watch this for when the Android branch lands 👀

**Comment by bretthoerner** [comment]
My bad. You're right. You need to use DefaultRavenFactory though.

**Comment by bgerstle** [comment]
Pretty sure we were—keep in mind that manually captured exceptions were going through, e.g. `Raven.sendException(new IllegalStateException(...))`

**Comment by bgerstle** [comment]
@bretthoerner somewhat related: I've contacted support about this but wanted to ping you as well: does the platform support desymbolicating Java stack traces?  If not, what's your general recommendation for having readable stack traces in your events?

**Comment by bgerstle** [comment]
Sorry, that's symbolicate, not desymbolicate

**Comment by bretthoerner** [comment]
Can you give an example? This is what I have in the raw stacktrace from my Android test app.

![raw](http://i.imgur.com/YR4G6Rq.png)

**Comment by Hazer** [comment]
Just my 2 cents about `Application.onTerminate` it isn't called most of the time, official documentation states:

> This method is for use in emulated process environments. It will never be called on a production Android device, where processes are removed by simply killing them; no user code (including this callback) is executed when doing so.

`UncaughtExceptionHandler` is the only option for exceptions and hand made callbacks counting Activities opened/closed through `Application.ActivityLifecycleCallbacks` is the only option for "termination" detection.

**Comment by Hazer** [comment]
Below snippet took from @bgerstle `setupUncaughtExceptionHandler`
```
Log.e("An uncaught exception occurred: " + e);
Raven.capture(e);
if (defaultUncaughtExceptionHandler != null) {
    defaultUncaughtExceptionHandler.uncaughtException(t, e);
}
```

@bretthoerner If I understood right, Rave.capture, delegates to AsyncConnection, and if failed to send or the ShutdownHook is called, then you save to disk.

Using the above code, ShutdownHook will not be called every time. The DefaultUncaughtExceptionHandler from Android, may kill the entire JVM process, the ExecutorService callbacks will not work in this case.

Almost every crash reporting lib that i've read, create and save the event to disk before any other operation can be done, its heavy but works.

There are 2 more techniques that can work and don't need to write to disk first:

- Use an Service with its own process, send the event to the service and then let the main process be killed. It's heavy, each android process, if I remember right, uses 2mb only to exist. And each process will have its own `android.app.Application` instance, and if the user subclassed it, and put logic in there as if it where a Singleton, there may be problems. Firebase Crash Reporting use this technique.
- Put the event into an PendingIntent, schedule this intent into an Alarm to fire soon, and kill the application yourself instead of using the DefaultUncaughtExceptionHandler. Not a clean solution, may create colateral effects harder to track than an `Application` with more logic than needed.

In the past, i've used a hybrid solution consisting of writing-to-disk-first, and then killing the app myself, and opening another process with a custom User Feedback Activity, saying the developers were informed of the problem, and asking for more details/contact info. When the new process opens, it creates a new `Application` instance, this instance had my Crash Report Client, and that client tries to send the in-disk-event's fifo when was starting.

Sorry for the long post, and for maybe if I was the obvious guy, but I was trying to shed some light, I really like Sentry and it really was missing an official Android Client.

**Comment by bretthoerner** [comment]
Trying to write to disk *before* sending here, but I have some work to do: https://github.com/getsentry/raven-java/pull/305

**Comment by bretthoerner** [comment]
We now write events to disk first when buffering is enabled (true on Android by default) on `master`, release soon.
