### ISSUE TITLE
Custom RavenFactory cannot be used with raven-log4j

### ISSUE THREAD

**Issue by georgms** [getsentry/raven-java#267]
It seems that currently a custom `RavenFactory` cannot be used with `raven-log4j`.

My `pom.xml`:

``` xml
<dependency>
    <groupId>com.getsentry.raven</groupId>
    <artifactId>raven-log4j</artifactId>
    <version>7.8.0</version>
</dependency>
```

My `log4j.properties`:

``` properties
log4j.appender.SentryAppender=com.getsentry.raven.log4j.SentryAppender
log4j.appender.SentryAppender.extraTags=shopkey,method
log4j.appender.SentryAppender.dsn=https://user:pass@sentry.io/id
log4j.appender.SentryAppender.Threshold=WARN
log4j.appender.SentryAppender.ravenFactory=com.company.CustomRavenFactory
```

My `RavenFactory`:

``` java
package com.company;

import com.getsentry.raven.Raven;
import com.getsentry.raven.dsn.Dsn;
import com.getsentry.raven.event.EventBuilder;
import com.getsentry.raven.event.helper.EventBuilderHelper;

public class CustomRavenFactory extends RavenFactory {

    @Override
    public Raven createRavenInstance(Dsn dsn) {
        Raven raven = RavenFactory.ravenInstance(dsn);

        raven.addBuilderHelper(new EventBuilderHelper() {

            @Override
            public void helpBuildingEvent(EventBuilder eventBuilder) {
                /* Get the release number from build,properties */
                eventBuilder.withRelease(...);
            }
        });

        return raven;
    }
}
```

The error message I am getting:

``` log4j
log4j:ERROR An exception occurred during the creation of a Raven instance
java.lang.IllegalStateException: Couldn't create a raven instance for: 'Dsn{uri=https://sentry.io/}'; ravenFactoryName: CustomRavenFactory; skipped factories: com.getsentry.raven.DefaultRavenFactory; no factories tried!
```

I looked into the code a bit and it seems that  `CustomRavenFactory.createRavenInstance(Dsn)` is never called, because:
- `SentryAppender#initRaven` calls `RavenFactory#ravenInstance(new Dsn(dsn), ravenFactory);`
- `RavenFactory#ravenInstance(Dsn, String)` will iterate over all factories obtained from `RavenFactory#getRegisteredFactories`
- `RavenFactory#getRegisteredFactories` however will not return `CustomRavenFactory`
- so `RavenFactory#ravenInstance` will skip `CustomRavenFactory`

Am I missing something?

Oh, and by the way, all I want to do is set the release programatically. Maybe there is an easier way for this...

**Comment by bretthoerner** [comment]
Hm, you make a good point. Re-reading the code, I feel like you'd have to either,

1. manually register the class: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/RavenFactory.java#L25-L36
2. add a `ServiceLoader` provider file to your project so that your custom class is automatically found: https://github.com/getsentry/raven-java/blob/master/raven/src/main/resources/META-INF/services/com.getsentry.raven.RavenFactory

We can definitely fix the documentation if 2 works for you.

OR maybe we should blindly try to construct your class via reflection? I will look into that, but solution 2 should hopefully get you going more quickly.

**Comment by georgms** [comment]
Option 2 worked flawlessly, thanks!
